name: Deploy Node.js App to Vps
on:
  push:
    branches:
      - main

jobs:
 deploy:
   runs-on: ubuntu-latest


   steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy Via SSH
      uses : appleboy/ssh-action@v0.1.5
      with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: 
              cd /path/to/your/app
              docker-compose down
              docker-compose up -d --build
